name: (Shared) Named Lock Platform Tester

on:
  workflow_call:
    inputs:
      matrix-config:
        description: 'The Matrix as a JSON String to be used for the Matrix Strategy'
        required: true
        type: string

jobs:
  compose:
    name: ${{ matrix.config.name }} Composition
    runs-on: ${{ matrix.config.runner }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - ${{ fromJSON(inputs.matrix-config) }}

    env:
      GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    outputs:
      DOCKERIZATION: ${{ steps.dockerize.outputs.configurations }}

    steps:
      - name: Echo Default Cache Paths
        if: matrix.config.system_information.kernel_family == 'unix'
        env:
          DART_SDK_DIR_DEFAULT: /opt/hostedtoolcache/dart-sdk/
          HOME_BREW_DIR_DEFAULT: /usr/local
          PROTOC_SDK_DIR_DEFAULT: /opt/hostedtoolcache/protoc/
          DCLI_BIN_DIR_DEFAULT: .dcli/bin/
          PUB_CACHE_DIR_DEFAULT: .pub-cache/
        run: |
          echo "HOME_BREW_DIR=$(command -v brew >/dev/null 2>&1 && echo "$(brew --prefix)" || echo $HOME_BREW_DIR_DEFAULT)" >> $GITHUB_ENV
          echo "PROTOC_SDK_DIR=$(echo $PROTOC_SDK_DIR_DEFAULT)" >> $GITHUB_ENV
          echo "DCLI_BIN_DIR=$HOME/${DCLI_BIN_DIR_DEFAULT}" >> $GITHUB_ENV
          echo "PUB_CACHE_DIR=$HOME/${PUB_CACHE_DIR_DEFAULT}" >> $GITHUB_ENV
          echo "DART_SDK_DIR=$(echo $DART_SDK_DIR_DEFAULT)" >> $GITHUB_ENV

      - name: Echo Default Cache Paths [Windows]
        if: matrix.config.system_information.operating_system_family == 'windows'
        env:
          DART_SDK_DIR_DEFAULT: C:\tools\dart-sdk\bin
          PROTOC_SDK_DIR_DEFAULT: C:\tools\protoc\bin
        run: |
          echo "DART_SDK_DIR=$($env:DART_SDK_DIR_DEFAULT)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "PROTOC_SDK_DIR=$($env:PROTOC_SDK_DIR_DEFAULT)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          
          $program_files = $env:ProgramFiles
          $dcli_bin_dir = Join-Path -Path $program_files -ChildPath "\.dcli\bin"
          echo "DCLI_BIN_DIR=$dcli_bin_dir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "PUB_CACHE_DIR=$env:USERPROFILE\.pub-cache\" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Echo Initial Cache Locations
        run: |
          echo 'DART_SDK_DIR: ${{ env.DART_SDK_DIR }}'
          echo 'PROTOC_SDK_DIR: ${{ env.PROTOC_SDK_DIR }}'
          echo 'DCLI_BIN_DIR: ${{ env.DCLI_BIN_DIR }}'
          echo 'PUB_CACHE_DIR: ${{ env.PUB_CACHE_DIR }}'

      # TODO: Re-enable the cache for the dart sdk
      #      - name: Restore Cached Dart SDK
      #        uses: actions/cache@v3.3.1
      #        id: cache-dart-sdk
      #        with:
      #          path: ${{ env.DART_SDK_DIR }}
      #          key: dart-${{ matrix.config.system_information.operating_system_family }}-${{ matrix.config.system_information.kernel_architecture }}-${{ hashFiles('**/pubspec.lock') }}
      #          restore-keys: dart-${{ matrix.config.system_information.operating_system_family }}-${{ matrix.config.system_information.kernel_architecture }}-

      - name: Restore Cached Protobuf [Unix]
        uses: actions/cache@v3.3.1
        id: cache-protobuf
        with:
          path: ${{ env.PROTOC_SDK_DIR }}
          key: protobuf-${{ matrix.config.system_information.operating_system_family }}-${{ matrix.config.system_information.kernel_architecture }}-${{ hashFiles('**/PROTOC_VERSION') }}
          restore-keys: protobuf-${{ matrix.config.system_information.operating_system_family }}-${{ matrix.config.system_information.kernel_architecture }}-

    # TODO: Re-enable the cache for the pub dependencies
    #      - name: Restore Cached Pub Dependencies
    #        uses: actions/cache@v3.3.1
    #        id: cache-pub-dependencies
    #        with:
    #          path: ${{ env.PUB_CACHE_DIR }}
    #          key: pub-cache-${{ matrix.config.system_information.operating_system_family }}-${{ matrix.config.system_information.kernel_architecture }}-${{ hashFiles('**/pubspec.lock') }}
    #          restore-keys: pub-cache-${{ matrix.config.system_information.operating_system_family }}-${{ matrix.config.system_information.kernel_architecture }}-

      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          lfs: true

      - name: Echo Matrix Configuration
        run: |
          configuration=$(jq -c '.' <<< '${{ toJSON(matrix.config) }}')
          echo $configuration
        shell: bash

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.5.0
        with:
          architecture: ${{ matrix.config.architecture.dart }}

      - name: Install Dart Dependencies
        run: dart pub get

      - name: Enable Developer Command Prompt
        if: matrix.config.system_information.operating_system_family == 'windows'
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Compile C++ code
        if: matrix.config.system_information.operating_system_family == 'windows'
        run: |
          cl /EHsc test\native_create_semaphore_w.cpp /Fe:test\native_create_semaphore_w.exe

      - name: Verify executable creation
        if: matrix.config.system_information.operating_system_family == 'windows'
        run: |
          if (Test-Path test\native_create_semaphore_w.exe) {
            Write-Host "Executable created successfully ✅"
          } else {
            Write-Error "Executable does not exist"
            exit 1
          }
#
#      - name: Run C++ code as a background process
#        run: |
#          Start-Process -FilePath "test\native_create_mutex_w.exe" -NoNewWindow

      - name: Run Dart Code
        if: matrix.config.system_information.operating_system_family == 'windows'
        run: dart run test/create_mutex_w.dart

#      - name: Run Dart Tests
#        run: dart test .
